import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import packageJson from '../package.json';

export default defineConfig({
    plugins: [react()],
    base: '', // Use relative paths for NeutralinoJS
    define: {
        __APP_VERSION__: JSON.stringify(packageJson.version)
    },
    build: {
        outDir: '../dist',
        emptyOutDir: true,
    },
    optimizeDeps: {
        include: [
            '@mui/material',
            '@mui/icons-material',
            '@emotion/react',
            '@emotion/styled',
            'react-chessboard',
            'chess.js',
            'socket.io-client',
            '@mui/material/AppBar',
            '@mui/material/Box',
            '@mui/material/Button',
            '@mui/material/Card',
            '@mui/material/CardContent',
            '@mui/material/Chip',
            '@mui/material/Dialog',
            '@mui/material/DialogTitle',
            '@mui/material/DialogContent',
            '@mui/material/DialogActions',
            '@mui/material/Divider',
            '@mui/material/Drawer',
            '@mui/material/FormControl',
            '@mui/material/IconButton',
            '@mui/material/InputLabel',
            '@mui/material/LinearProgress',
            '@mui/material/List',
            '@mui/material/ListItemButton',
            '@mui/material/ListItemIcon',
            '@mui/material/ListItemText',
            '@mui/material/MenuItem',
            '@mui/material/Paper',
            '@mui/material/Select',
            '@mui/material/Slider',
            '@mui/material/Snackbar',
            '@mui/material/Alert',
            '@mui/material/Table',
            '@mui/material/TableBody',
            '@mui/material/TableCell',
            '@mui/material/TableContainer',
            '@mui/material/TableHead',
            '@mui/material/TableRow',
            '@mui/material/TextField',
            '@mui/material/ToggleButton',
            '@mui/material/ToggleButtonGroup',
            '@mui/material/Toolbar',
            '@mui/material/Tooltip',
            '@mui/material/Typography',
            '@mui/material/Avatar',
            '@mui/material/CircularProgress',
            '@mui/material/CssBaseline',
            '@mui/material/styles',
            '@mui/material/useMediaQuery',
        ],
    },
});
